excluded:
  - .build
  - Tests

disabled_rules:
  - trailing_whitespace
  - line_length
  - file_length
  - type_body_length
  - function_body_length
  - cyclomatic_complexity

opt_in_rules:
  - empty_count
  - empty_string
